Repository maistra/maistra-test-tool, pull requests merged in 2023-07, with the labels that each got.

#606 OSSM-4367 adding git to DockerFile
  Dockerfile
Labels: size/XS, okay to merge

#605 OSSM-4360 Avoid flaky in certmanager test cases
  pkg/certmanageroperator/install.go
  pkg/certmanageroperator/yaml/cert-manager-operator.yaml
  pkg/certmanageroperator/yaml/root-ca.yaml
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/main_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/pod_commands.go
Labels: size/L, okay to merge

#608 OSSM-4380 TestAuthorizationTCPTraffic increase attempts for assertPortTcpEchoAccepted(t, ns, podIP, "9002")
  pkg/tests/tasks/security/authorization/tcp_test.go
Labels: size/XS, okay to merge

#607 OSSM-4309 Revert changes to WaitCondition, create WaitForPhase and avoid flaky for not created csv
  pkg/certmanageroperator/install.go
  pkg/tests/tasks/observability/custom_prometheus_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/pod_commands.go
Labels: size/M, okay to merge

#609 Move uninstall from certmanager test
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
Labels: okay to merge

#375 OSSM-3343 Create test case for IOR
  pkg/tests/ossm/ior_test.go
  pkg/tests/ossm/setup.go
  templates/smcp-templates/v2.4/cr_2.4_default_template.yaml
Labels: size/L, okay to merge

#440 OSSM-3770 Add test case for Prometheus scopes auto-update
  pkg/tests/ossm/prometheus_scoped_scraping_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/pod_commands.go
Labels: size/L, okay to merge

#610 OSSM-4195 adding more information to step in failure
  pkg/tests/tasks/observability/custom_prometheus_test.go
Labels: size/XS, okay to merge

#611 OSSM-4451 Skip TestOperatorCanUpdatePrometheusConfigMap changes and avoid flakiness
  pkg/tests/ossm/prometheus_scoped_scraping_test.go
  pkg/util/oc/pod_commands.go
Labels: size/S, okay to merge

#612 OSSM-4474 TestAuthorizationTCPTraffic fix flaky
  pkg/tests/tasks/security/authorization/tcp_test.go
Labels: size/M, okay to merge

#613 OSSM-4472 Fix ior test case in versions less than 2.4
  pkg/tests/ossm/ior_test.go
Labels: size/XS, okay to merge

#614 OSSM-4449 Increase coverage by adding subtestcase SMCP manageNetworkPolicy true
  pkg/tests/tasks/observability/main_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/observability/yaml/mesh.tmpl.yaml
  pkg/tests/tasks/observability/yaml/network-policy.yaml
Labels: size/L, okay to merge
