Repository maistra/maistra-test-tool, pull requests merged in 2023-04, with the labels that each got.

#398 Test CI tide
  test.txt
Labels: size/XS, okay to merge

#402 fix error in WaitCondition
  pkg/util/oc/pod_commands.go
Labels: size/XS, okay to merge

#409 Ensure `make build` compiles the test binaries
  Makefile
  scripts/compiletests.sh
Labels: size/S, okay to merge

#408 refactor the t36 test case
  pkg/ossm/bug_multiple_smcp.go
  pkg/ossm/yaml_vars.go
  tests/test_cases.go
Labels: size/M, okay to merge

#411 Fix tests that fail because the "Rosa" field is missing in the template input
  pkg/tests/non-dependant/yaml.vars.go
  pkg/tests/ossm/setup.go
  pkg/tests/tasks/security/authentication/yaml_vars.go
  pkg/tests/tasks/security/authorization/yaml.vars.go
  pkg/tests/tasks/traffic/egress/yaml_vars.go
  pkg/util/template/template.go
Labels: size/M, okay to merge

#401 OSSM-3639 Refactor TestBookinfo (A2)
  pkg/tests/ossm/smoke_test.go
Labels: size/M, okay to merge

#415 Ensure curl() in deny_test.go doesn't interfere with the curl package
  pkg/tests/tasks/security/authorization/deny_test.go
Labels: size/S, okay to merge

#414 OSSM-3715: Refactor TestAuthorizationHTTPTraffic (T20)
  README.md
  go.mod
  go.sum
  pkg/tests/tasks/security/authorization/http_test.go
  pkg/tests/tasks/security/authorization/yaml.vars.go
  pkg/tests/tasks/security/authorization/yaml_configs.go
  pkg/tests/tasks/traffic/traffic_shifting_test.go
  pkg/util/check/assert/http_response.go
  pkg/util/check/common/http_response.go
  pkg/util/check/require/http_response.go
  pkg/util/curl/curl.go
  pkg/util/oc/pod_commands.go
Labels: size/L, okay to merge

#416 Fix deny_test function name typo
  pkg/tests/tasks/security/authorization/deny_test.go
Labels: size/S

#418 Fix typo. Replace httbin with httpbin
  pkg/tests/tasks/traffic/egress/access_external_services_test.go
  pkg/tests/tasks/traffic/egress/yaml_configs.go
  pkg/tests/tasks/traffic/traffic_mirroring_test.go
Labels: size/XS, okay to merge

#422 OSSM-3726 Refactor TestMigration (T19)
  pkg/app/sleep.go
  pkg/examples/yaml_vars.go
  pkg/tests/tasks/security/authentication/mtls_migration_test.go
  pkg/tests/tasks/security/authentication/yaml_configs.go
  pkg/util/oc/oc.go
Labels: size/L, okay to merge

#423 OSSM-3727 Refactor TestAuthPolicy (T18)
  pkg/app/httpbin.go
  pkg/examples/yaml_vars.go
  pkg/tests/tasks/security/authentication/auth_test.go
  pkg/tests/tasks/security/authentication/mtls_migration_test.go
  pkg/tests/tasks/security/authentication/yaml_configs.go
  pkg/tests/tasks/security/authentication/yaml_vars.go
  pkg/util/curl/curl.go
Labels: size/XL, okay to merge

#419 OSSM-3707 Refactor TestTLSVersionSMCP (T26), OSSM-3740 Refactor TestSSL (T27)
  pkg/tests/ossm/smcp_tls_ssl_test.go
  pkg/tests/ossm/testssl_test.go
Labels: size/L, okay to merge

#405 OSSM-3658 Refactor TestIstioPodProbesFails (T35)
  pkg/tests/ossm/bug_istiopods_test.go
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/setup.go
  pkg/util/oc/pod_commands.go
  pkg/util/testUtil.go
  scripts/smmr/clean_members.sh
  scripts/smmr/create_members.sh
Labels: size/L, okay to merge

#424 OSSM-3721 Refactor T21 TestAuthorizationTCPTraffic
  pkg/app/echo-v1.go
  pkg/app/echo-v2.go
  pkg/app/echo.go
  pkg/examples/yaml_vars.go
  pkg/tests/tasks/security/authorization/tcp_test.go
  pkg/tests/tasks/security/authorization/yaml_configs.go
  pkg/util/oc/pod_commands.go
  testdata/examples/x86/tcp-echo/tcp-echo-v1.yaml
  testdata/examples/x86/tcp-echo/tcp-echo-v2.yaml
Labels: size/XL, ok-to-test, okay to merge

#413 OSSM-3665 Refactor TestInitContainer (T33)
  pkg/tests/ossm/initContainer_test.go
  pkg/tests/ossm/initcontainer_test.go
  pkg/tests/ossm/yaml/deployment-sleep-init.yaml
Labels: size/L, okay to merge

#426 OSSM-3744 Refactor TestMustGather (T30)
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/util/shell/shell_helper.go
Labels: size/M, okay to merge

#425 OSSM-3738 Refactor External Authorization (T37)
  pkg/tests/tasks/security/authorization/common.go
  pkg/tests/tasks/security/authorization/deny_test.go
  pkg/tests/tasks/security/authorization/ext_auth_test.go
Labels: size/L, okay to merge

#435 OSSM-3692 Refactor JWT Authorization (T22)
  pkg/tests/tasks/security/authorization/common.go
  pkg/tests/tasks/security/authorization/deny_test.go
  pkg/tests/tasks/security/authorization/ext_auth_test.go
  pkg/tests/tasks/security/authorization/jwt_test.go
  pkg/tests/tasks/security/authorization/yaml_configs.go
Labels: size/L, okay to merge

#430 OSSM-3737 Refactor TestSMCPAnnotations (T29)
  pkg/tests/ossm/smcp_annotation_test.go
  pkg/tests/ossm/testssl_test.go
  pkg/tests/ossm/yaml/deployment-testenv-p.yaml
  pkg/tests/ossm/yaml/deployment-testenv-x86.yaml
  pkg/tests/ossm/yaml/deployment-testenv-z.yaml
  pkg/util/env/env.go
Labels: size/L, okay to merge

#429 OSSM-3741 Refactor TestRateLimiting T28
  pkg/app/redis.go
  pkg/examples/yaml_vars.go
  pkg/tests/ossm/ratelimit_test.go
  pkg/tests/ossm/yaml/smcp-patch-rate-limiting.yaml
  pkg/util/env/env.go
  pkg/util/version/version.go
  pkg/util/version/version_test.go
Labels: size/L, okay to merge

#437 Prevent oc.DeleteFile from failing if resource doesn't exist
  pkg/util/oc/oc.go
Labels: size/XS, okay to merge

#436 OSSM-3735 Refactor TestTcpTrafficShifting (T4)
  pkg/tests/tasks/traffic/traffic_shifting_test.go
  pkg/tests/tasks/traffic/traffic_tcp_shifting_test.go
  pkg/tests/tasks/traffic/yaml/tcp-echo-20-v2.yaml
  pkg/tests/tasks/traffic/yaml/tcp-echo-all-v1.yaml
Labels: size/L, okay to merge

#431 OSSM-3432 Cert Manager (T39)
  pkg/tests/tasks/security/certificate/cert_manager_test.go
Labels: size/L, okay to merge

#442 Fix TestAuthorizationJWT
  pkg/tests/tasks/security/authorization/common.go
  pkg/tests/tasks/security/authorization/jwt_test.go
Labels: size/M, okay to merge

#432 OSSM-3729 Refactor TestAccessExternalServices (T11)
  pkg/tests/tasks/traffic/egress/access_external_services_test.go
  pkg/tests/tasks/traffic/egress/egress_common.go
  pkg/tests/tasks/traffic/egress/egress_gateways_test.go
  pkg/tests/tasks/traffic/egress/yaml_configs.go
Labels: size/L, okay to merge

#446 OSSM-3702 Remove obsolete TestExtensionInstall
  pkg/tests/ossm/sme_install_test.go
  pkg/tests/ossm/yaml/servicemeshextension-header-append.yaml
Labels: size/L, okay to merge

#448 Fix pod.MatchingSelector()
  pkg/tests/ossm/initcontainer_test.go
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/util/oc/pod_commands.go
  pkg/util/pod/pods.go
Labels: size/S, okay to merge

#444 OSSM-3785 Refactor TestEgressTLSOrigination (T12)
  pkg/tests/tasks/traffic/egress/egress_common.go
  pkg/tests/tasks/traffic/egress/egress_gateways_test.go
  pkg/tests/tasks/traffic/egress/egress_tls_origination_test.go
Labels: size/L, okay to merge

#445 OSSM-3777 Refactor TestTLSOriginationFileMount (T14)
  pkg/app/nginx.go
  pkg/examples/yaml_vars.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_file_mount_test.go
  pkg/tests/tasks/traffic/egress/yaml_configs.go
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
Labels: size/XL, okay to merge

#454 Remove unused files
  pkg/tests/ossm/yaml/deployment-testssl-p.yaml
  pkg/tests/ossm/yaml/deployment-testssl-x86.yaml
  pkg/tests/ossm/yaml/deployment-testssl-z.yaml
Labels: size/M, okay to merge

#460 Ensure TestSMCPAddons doesn't affect other tests
  pkg/tests/ossm/smcp_addons_test.go
  pkg/util/oc/oc_struct.go
Labels: size/XS, okay to merge

#459 Ensure TestAuthorizationTCPTraffic doesn't break other tests
  pkg/tests/tasks/security/authorization/tcp_test.go
Labels: size/XS, okay to merge

#452 Print output when a command fails
  pkg/util/shell/shell_helper.go
Labels: size/XS, okay to merge

#455 Run TestSMCPAnnotations subtests in parallel
  pkg/tests/ossm/smcp_annotation_test.go
  pkg/util/test/test_helper.go
Labels: size/S, okay to merge

#453 Automatically disable logrus for all refactored tests
  pkg/tests/non-dependant/smcp_install_test.go
  pkg/tests/ossm-federation/federation_failover_test.go
  pkg/tests/ossm-federation/federation_traffic_splitting_test.go
  pkg/tests/ossm/bug_istiopods_test.go
  pkg/tests/ossm/initcontainer_test.go
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/operator/operator_deadlock_test.go
  pkg/tests/ossm/operator/operator_readiness_test.go
  pkg/tests/ossm/ratelimit_test.go
  pkg/tests/ossm/smcp_addons_test.go
  pkg/tests/ossm/smcp_annotation_test.go
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/tests/ossm/smcp_tls_ssl_test.go
  pkg/tests/ossm/smoke_test.go
  pkg/tests/ossm/testssl_test.go
  pkg/tests/tasks/security/authentication/auth_test.go
  pkg/tests/tasks/security/authentication/mtls_migration_test.go
  pkg/tests/tasks/security/authorization/deny_test.go
  pkg/tests/tasks/security/authorization/ext_auth_test.go
  pkg/tests/tasks/security/authorization/http_test.go
  pkg/tests/tasks/security/authorization/jwt_test.go
  pkg/tests/tasks/security/authorization/tcp_test.go
  pkg/tests/tasks/traffic/circuit_breaking_test.go
  pkg/tests/tasks/traffic/egress/access_external_services_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_file_mount_test.go
  pkg/tests/tasks/traffic/egress/egress_tls_origination_test.go
  pkg/tests/tasks/traffic/egress/egress_wildcard_hosts_test.go
  pkg/tests/tasks/traffic/fault_injection_test.go
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/tests/tasks/traffic/request_routing_test.go
  pkg/tests/tasks/traffic/request_timeouts_test.go
  pkg/tests/tasks/traffic/traffic_mirroring_test.go
  pkg/tests/tasks/traffic/traffic_shifting_test.go
  pkg/tests/tasks/traffic/traffic_tcp_shifting_test.go
  pkg/util/hack/hacks.go
  pkg/util/test/test.go
Labels: size/L, okay to merge

#462 Make TestSSL retry only 10 times, because each attempt takes over 5s
  pkg/tests/ossm/testssl_test.go
Labels: size/XS, okay to merge

#456 OSSM-3793 Speed up TestSSL
  pkg/tests/ossm/testssl_test.go
Labels: size/M, okay to merge

#463 Proper clean up after TestSMCPAnnotations
  pkg/tests/ossm/smcp_annotation_test.go
Labels: size/XS, okay to merge

#464 Fix images.yaml
  images.yaml
Labels: size/XS, okay to merge

#465 Skip TestClusterWideMode and TestOperatorPodHonorsReadinessProbe in v2.3-
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/operator/operator_readiness_test.go
Labels: size/XS, okay to merge

#466 Clean up and fix TestTrustDomainMigration
  pkg/tests/tasks/security/authorization/trust_domain_test.go
  pkg/tests/tasks/security/authorization/yaml_configs.go
Labels: size/L, okay to merge

#449 OSSM-3780 Refactor TestTLSOriginationSDS (T15)
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_file_mount_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_sds_test.go
Labels: size/L, okay to merge

#470 OSSM-3767 Refactor TestIngressWithoutTlsTermination (T10)
  pkg/tests/tasks/traffic/ingress/ingress_without_tls_termination_test.go
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/tests/tasks/traffic/ingress/yaml_vars.go
  pkg/util/istio/istio.go
Labels: size/L, okay to merge

#472 OSSM-3694 Refactor TestSMCPMutiple (T36)
  pkg/tests/non-dependant/bug_multiple_smcp_test.go
  pkg/tests/ossm/bug_multiple_smcp_test.go
  pkg/tests/ossm/setup.go
  pkg/tests/ossm/yaml/smcp_meta_v2.3.yaml
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
  pkg/util/template/template.go
Labels: size/L, okay to merge

#438 OSSM-3756 Refactor TestExternalCert (T17)
  pkg/tests/tasks/security/certificate/external_ca_test.go
  pkg/tests/tasks/security/certificate/yaml_configs.go
  pkg/tests/tasks/security/certificate/yaml_vars.go
  pkg/util/env/env.go
  pkg/util/template/images.go
  pkg/util/test/test.go
Labels: size/L, okay to merge

#473 Remove NotRefactoredYet() since all tests have been refactored
  pkg/util/test/test.go
Labels: size/XS, okay to merge

#474 Allow use of TestHelper in setup functions
  pkg/tests/ossm/setup.go
  pkg/util/test/suite.go
  pkg/util/test/test_helper_setup.go
Labels: size/L, okay to merge

#475 Fix make check
  scripts/compiletests.sh
Labels: size/XS, okay to merge

#476 Clean up TestAuthPolicy
  pkg/tests/tasks/security/authentication/auth_test.go
Labels: size/S, okay to merge

#477 Fix type in TestSMCPMultiple() name
  pkg/tests/non-dependant/bug_multiple_smcp_test.go
Labels: size/XS, okay to merge

#478 Delint code (remove unused code, replace calls of deprecated functions, fix typos, etc.)
  README.md
  go.mod
  pkg/tests/non-dependant/smcp_install_test.go
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/ratelimit_test.go
  pkg/tests/ossm/setup.go
  pkg/tests/tasks/security/authorization/yaml.vars.go
  pkg/tests/tasks/security/certificate/yaml_vars.go
  pkg/tests/tasks/traffic/ingress/yaml_vars.go
  pkg/tests/tasks/traffic/yaml_vars.go
  pkg/util/common.go
  pkg/util/compare.go
  pkg/util/env/env.go
  pkg/util/io.go
  pkg/util/kube.go
  pkg/util/ocp.go
  pkg/util/request/headers.go
  pkg/util/request/multiple.go
  pkg/util/request/tls.go
  pkg/util/shell.go
  pkg/util/shell/shell_helper.go
  pkg/util/testUtil.go
  sampleCerts/README.md
  scripts/.golangci.yaml
Labels: size/XL, okay to merge

#481 Use helpers in setup and remove old util functions
  pkg/app/bookinfo.go
  pkg/app/sleep.go
  pkg/tests/ossm/setup.go
  pkg/tests/ossm/smoke_test.go
  pkg/tests/tasks/traffic/egress/egress_common.go
  pkg/tests/tasks/traffic/egress/egress_gateways_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_file_mount_test.go
  pkg/tests/tasks/traffic/egress/egress_tls_origination_test.go
  pkg/util/common.go
  pkg/util/curl/curl.go
  pkg/util/kube.go
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
  pkg/util/oc/pod_commands.go
  pkg/util/retry.go
  pkg/util/shell.go
  pkg/util/shell/shell_helper.go
  pkg/util/test/setup_logger.go
  pkg/util/test/test.go
  pkg/util/test/test_flaky.go
  pkg/util/test/test_helper.go
  pkg/util/test/test_helper_retry.go
  pkg/util/test/test_helper_setup.go
  pkg/util/test/test_test.go
  pkg/util/testUtil.go
Labels: size/XL, okay to merge

#450 OSSM-3314: Fix test of integration with cert-manager-istio-csr
  pkg/tests/tasks/security/certificate/cert_manager_test.go
  pkg/tests/tasks/security/certificate/external_ca_test.go
  pkg/tests/tasks/security/certificate/main_test.go
  pkg/util/helm/helm.go
  pkg/util/oc/oc.go
  pkg/util/oc/pod_commands.go
Labels: size/L, okay to merge

#482 OSSM-3794 Move SMCP/SMMR setup into individual tests
  pkg/tests/ossm/bug_istiopods_test.go
  pkg/tests/ossm/initcontainer_test.go
  pkg/tests/ossm/main_test.go
  pkg/tests/ossm/ratelimit_test.go
  pkg/tests/ossm/setup.go
  pkg/tests/ossm/smcp_addons_test.go
  pkg/tests/ossm/smcp_annotation_test.go
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/tests/ossm/smcp_tls_ssl_test.go
  pkg/tests/ossm/smoke_test.go
  pkg/tests/ossm/testssl_test.go
  pkg/tests/tasks/security/authentication/auth_test.go
  pkg/tests/tasks/security/authentication/main_test.go
  pkg/tests/tasks/security/authentication/mtls_migration_test.go
  pkg/tests/tasks/security/authorization/deny_test.go
  pkg/tests/tasks/security/authorization/ext_auth_test.go
  pkg/tests/tasks/security/authorization/http_test.go
  pkg/tests/tasks/security/authorization/jwt_test.go
  pkg/tests/tasks/security/authorization/main_test.go
  pkg/tests/tasks/security/authorization/tcp_test.go
  pkg/tests/tasks/security/authorization/trust_domain_test.go
  pkg/tests/tasks/traffic/circuit_breaking_test.go
  pkg/tests/tasks/traffic/egress/access_external_services_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_file_mount_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_sds_test.go
  pkg/tests/tasks/traffic/egress/egress_tls_origination_test.go
  pkg/tests/tasks/traffic/egress/egress_wildcard_hosts_test.go
  pkg/tests/tasks/traffic/egress/main_test.go
  pkg/tests/tasks/traffic/fault_injection_test.go
  pkg/tests/tasks/traffic/ingress/ingress_gateways_test.go
  pkg/tests/tasks/traffic/ingress/ingress_without_tls_termination_test.go
  pkg/tests/tasks/traffic/ingress/main_test.go
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/tests/tasks/traffic/main_test.go
  pkg/tests/tasks/traffic/request_routing_test.go
  pkg/tests/tasks/traffic/request_timeouts_test.go
  pkg/tests/tasks/traffic/traffic_mirroring_test.go
  pkg/tests/tasks/traffic/traffic_shifting_test.go
  pkg/tests/tasks/traffic/traffic_tcp_shifting_test.go
Labels: size/L, okay to merge

#484 Rename TestExtAuthz to TestEnvoyExtAuthzHttpExtensionProvider and adapt it for 2.4
  pkg/tests/tasks/security/authorization/ext_auth_test.go
Labels: size/M, okay to merge

#486 Ensure TestSMCPMultiple doesn't affect the next test
  pkg/tests/non-dependant/bug_multiple_smcp_test.go
Labels: size/XS, okay to merge

#485 OSSM-3803 Move extensionProviders to SMCP.spec.meshConfig.extensionProviders
  pkg/tests/tasks/security/authorization/ext_auth_test.go
Labels: size/S, okay to merge

#483 OSSM-3790 Add TestSMM and TestDeployOnInfraNodes
  go.mod
  go.sum
  pkg/tests/ossm/deploy_on_infra_test.go
  pkg/tests/ossm/smm_test.go
  pkg/tests/tasks/security/authentication/auth_test.go
  pkg/tests/tasks/security/authentication/mtls_migration_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
  pkg/util/oc/pod_commands.go
Labels: size/L, okay to merge

#488 Print the failure detail message in the same line
  pkg/util/check/assert/common.go
  pkg/util/check/require/common.go
Labels: size/XS, okay to merge

#490 OSSM-3778 Run against each supported SMCP version
  Dockerfile
  pkg/tests/non-dependant/bug_multiple_smcp_test.go
  pkg/tests/non-dependant/smcp_install_test.go
  pkg/tests/non-dependant/yaml.vars.go
  pkg/tests/ossm-federation/federation_common.go
  pkg/tests/ossm-federation/testdata/failover/east-mesh/smcp.yaml
  pkg/tests/ossm-federation/testdata/failover/west-mesh/smcp.yaml
  pkg/tests/ossm-federation/testdata/traffic-splitting/east-mesh/smcp.yaml
  pkg/tests/ossm-federation/testdata/traffic-splitting/west-mesh/smcp.yaml
  pkg/tests/ossm-federation/testdata/traffic-splitting/west-mesh/smcp_custom_cert.yaml
  pkg/tests/ossm/deploy_on_infra_test.go
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/operator/operator_deadlock_test.go
  pkg/tests/ossm/operator/operator_readiness_test.go
  pkg/tests/ossm/ratelimit_test.go
  pkg/tests/ossm/setup.go
  pkg/tests/ossm/yaml/smcp.yaml
  pkg/tests/ossm/yaml/smcp_v2.1.yaml
  pkg/tests/ossm/yaml/smcp_v2.2.yaml
  pkg/tests/ossm/yaml/smcp_v2.4.yaml
  pkg/tests/ossm/yaml_configs.go
  pkg/tests/tasks/security/certificate/cert_manager_test.go
  pkg/tests/tasks/security/certificate/external_ca_test.go
  pkg/tests/tasks/traffic/egress/yaml_vars.go
  pkg/util/env/env.go
  pkg/util/oc/pod_commands.go
  pkg/util/template/template.go
  pkg/util/test/test.go
  pkg/util/version/version.go
  pkg/util/version/version_test.go
  scripts/pipeline/run_all_tests.sh
  scripts/pipeline/run_one_test.sh
  scripts/runtests.sh
Labels: size/XL, okay to merge

#491 Remove unused env variables
  Dockerfile
  pkg/tests/ossm/setup.go
  tests/test.env
Labels: size/XS

#492 fix make test
  scripts/runtests.sh
Labels: size/XS, okay to merge

#493 Rename env vars
  Dockerfile
  README.md
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/tests/tasks/security/authorization/yaml.vars.go
  pkg/tests/tasks/traffic/ingress/yaml_vars.go
  pkg/tests/tasks/traffic/yaml_vars.go
  pkg/util/env/env.go
  scripts/runtests.sh
  tests/test.env
Labels: size/M, okay to merge

#489 Test cert-manager-istio-csr with Red Hat cert-manager operator
  pkg/tests/ossm/setup.go
  pkg/tests/tasks/security/certificate/cert_manager_test.go
  pkg/util/ns/namespaces.go
  pkg/util/oc/oc.go
  pkg/util/oc/pod_commands.go
Labels: size/L, okay to merge

#496 OSSM-3834 Use gotestsum instead of vanilla go test
  .gitignore
  Dockerfile
  scripts/runtests.sh
Labels: size/M, okay to merge

#497 Fix WaitPodReady()
  pkg/tests/ossm/deploy_on_infra_test.go
  pkg/util/oc/pod_commands.go
Labels: size/S, okay to merge, tide/merge-method-rebase

#498 Ensure all environment variables are read via env.GetXYZ() functions
  pkg/tests/ossm-federation/federation_failover_test.go
  pkg/tests/ossm-federation/main_test.go
  pkg/tests/ossm/setup.go
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/tests/tasks/security/authorization/yaml.vars.go
  pkg/tests/tasks/security/certificate/external_ca_test.go
  pkg/tests/tasks/traffic/ingress/yaml_vars.go
  pkg/tests/tasks/traffic/yaml_vars.go
  pkg/util/env/env.go
  pkg/util/oc/oc_struct.go
  pkg/util/template/images.go
  pkg/util/test/test.go
  tests/test.env
Labels: size/L, okay to merge

#499 OSSM-3836 Add env var LOG_FAILED_RETRY_ATTEMPTS
  pkg/util/env/env.go
  pkg/util/retry/retry.go
  pkg/util/test/test_helper_retry.go
Labels: size/M, okay to merge

#500 OSSM-3837: skip T40 test case until is fixed
  pkg/tests/ossm/deploy_on_infra_test.go
Labels: size/XS, okay to merge

#501 Ensure runtests.sh fails if gotestsum fails
  scripts/runtests.sh
Labels: size/XS, okay to merge

#503 Revert #501
  scripts/runtests.sh
Labels: size/XS, okay to merge

#504 OSSM-3840 Use `oc replace` when setting up SMCP
  pkg/tests/ossm/setup.go
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
  pkg/util/oc/pod_commands.go
Labels: size/M, okay to merge

#506 Automatically re-run failed tests
  scripts/runtests.sh
Labels: size/S, okay to merge

#508 Improve oc.WaitCondition
  pkg/util/oc/oc_struct.go
  pkg/util/oc/pod_commands.go
  pkg/util/retry/retry.go
Labels: size/M, okay to merge

#507 Run must-gather on each test failure
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/util/env/env.go
  pkg/util/test/subtest.go
  pkg/util/test/test.go
  pkg/util/test/test_helper.go
  scripts/runtests.sh
Labels: size/M, okay to merge

#509 Ensure TestExternalCertificate doesn't fail when TestCertManager runs before it
  pkg/tests/tasks/security/certificate/external_ca_test.go
Labels: size/S, okay to merge

#514 Add `make image` and `make push`
  Makefile
Labels: size/S, okay to merge

#512 Ensure TestTLSOrigination doesn't affect other tests
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_file_mount_test.go
Labels: size/XS, okay to merge

#511 Improve runtests
  pkg/util/env/env.go
  scripts/runtests.sh
Labels: size/L, okay to merge

#515 Update README.md
  README.md
Labels: size/L, okay to merge

#510 Fix TestCertManager
  pkg/tests/tasks/security/certificate/cert_manager_test.go
  pkg/util/check/assert/common.go
  pkg/util/check/assert/output.go
  pkg/util/check/common/output.go
  pkg/util/check/require/common.go
  pkg/util/check/require/output.go
Labels: size/M, okay to merge

#516 Fix oc.GetProxy()
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
Labels: size/S, okay to merge

#513 OSSM-3843 Create Routes when running against v2.4 with IOR disabled
  pkg/tests/tasks/traffic/ingress/ingress_gateways_test.go
  pkg/tests/tasks/traffic/ingress/ingress_without_tls_termination_test.go
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/tests/tasks/traffic/ingress/yaml_vars.go
Labels: size/M, okay to merge

#520 Make clean
  Makefile
Labels: size/XS, okay to merge

#521 Add OPERATOR_VERSION environment variable
  README.md
  scripts/runtests.sh
Labels: size/S, okay to merge

#522 Skip TestOperatorCanReconcileSMCPWhenIstiodOffline if SMCP version < 2.4
  pkg/tests/ossm/operator/operator_deadlock_test.go
Labels: okay to merge

#517 OSSM-3669: initial changes for interop pipeline support
  .dockerignore
  Dockerfile
Labels: size/M, okay to merge

#524 Ensure the cert-manager namespace is cleaned up in TestCertManager
  pkg/tests/tasks/security/certificate/cert_manager_test.go
Labels: size/XS, okay to merge

#525 Small fix to logs
  pkg/util/oc/pod_commands.go
  pkg/util/shell/shell_helper.go
Labels: size/S, okay to merge

#526 make test-cleanup
  Makefile
Labels: size/XS, okay to merge

#527 OSSM-3807: removing Jenkinsfile as new version is now used
  Jenkinsfile
Labels: okay to merge

#528 Make runtests.sh runnable on MacOS
  scripts/runtests.sh
Labels: size/S, okay to merge

#529 Fix TestMTlsMigration
  pkg/tests/tasks/security/authentication/mtls_migration_test.go
Labels: size/S, okay to merge

#530 Fix success message in CheckOutputContainsAny()
  pkg/util/check/common/output.go
Labels: size/XS, okay to merge

#531 Add missing t.Helper() in Skip() and Skipf()
  pkg/util/test/test_helper.go
Labels: size/XS, okay to merge

#532 Fix TestTrustDomainMigration
  pkg/tests/tasks/security/authorization/trust_domain_test.go
Labels: size/XS, okay to merge

#533 Make sure the token takes precedence over usr/pass when both are set
  scripts/runtests.sh
Labels: size/XS, okay to merge

#534 Skip CertManager test case in versions older than 2.4
  pkg/tests/tasks/security/certificate/cert_manager_test.go
Labels: size/XS, okay to merge

#537 Fix path
  Dockerfile
Labels: size/XS, okay to merge
