Repository maistra/maistra-test-tool, pull requests merged in 2023-02, with the labels that each got.

#365 Increase BaseDelay on CheckReady func
  pkg/util/kube.go
Labels: size/XS

#366 multiple_smcp_validation
  pkg/ossm/bug_multiple_smcp.go
  pkg/ossm/yaml_configs.go
  tests/test_cases.go
Labels: size/M

#367 Updating bookinfo images tags to 2.3.0
  testdata/examples/x86/bookinfo/bookinfo-db.yaml
  testdata/examples/x86/bookinfo/bookinfo-ratings-v2.yaml
  testdata/examples/x86/bookinfo/bookinfo.yaml
Labels: size/S

#369 Adding httpbin support for ipv6
  testdata/examples/x86/httpbin/httpbin.yaml
  testdata/examples/x86/httpbin/httpbin_legacy.yaml
  testdata/examples/x86/httpbin/httpbinv1.yaml
  testdata/examples/x86/httpbin/httpbinv2.yaml
Labels: size/XS

#364 Adding retry and fail for federation install script to avoid empty ce…
  pkg/federation/fed_single_cluster_install.go
  testdata/examples/failover/install.sh
  testdata/examples/federation/install.sh
Labels: size/M

#370 Adding support for IPv6 on testssl.sh
  pkg/ossm/smcp_tls_ssl.go
Labels: size/XS

#372 Automation for External Authorization
  pkg/tasks/security/authorization/externalauthorization.go
  pkg/tasks/security/authorization/yaml_configs.go
  pkg/util/kube.go
  tests/test_cases.go
Labels: size/L

#371 Set proxy variables from oc get proxy to avoid issue on IPv6 cluster
  Dockerfile
  pkg/examples/sleep.go
  pkg/ossm/init.go
  pkg/ossm/yaml_vars.go
  pkg/tasks/traffic/egress/egress_gateways.go
  pkg/tasks/traffic/egress/egress_tls_origination.go
  pkg/util/kube.go
  testdata/examples/x86/sleep/sleep.yaml
  testdata/examples/x86/sleep/sleep_legacy.yaml
  tests/test.env
Labels: size/L
