Repository maistra/maistra-test-tool, pull requests merged in 2023-08, with the labels that each got.

#615 OSSM-4601 Delete test from interop run and add retry to delete cert
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/util/oc/oc_struct.go
Labels: size/XS, okay to merge

#617 OSSM-4622 Fix verification for certManagerOperatorExists and increase retries
  pkg/certmanageroperator/install.go
Labels: size/S, okay to merge

#616 Add TestFederatedOpenShiftMonitoring
  pkg/tests/tasks/observability/custom_prometheus_test.go
  pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
  pkg/tests/tasks/observability/main_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/observability/yaml/federated-monitor.yaml
  pkg/tests/tasks/observability/yaml/federated-monitoring-mesh.tmpl.yaml
  pkg/util/prometheus/prometheus.go
  pkg/util/prometheus/prometheus_struct.go
Labels: size/L, okay to merge

#619 OSSM-4658 Update files to be able to work with 2.5.x operator version by default
  README.md
  pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/util/env/env.go
  scripts/runtests.sh
  templates/smcp-templates/v2.5/cr_2.5_default_template.yaml
Labels: size/M, okay to merge

#621 OSSM-4701 Adding the capability to enable or disable must gather after test case failure
  README.md
  pkg/util/env/env.go
  pkg/util/test/subtest.go
  pkg/util/test/test.go
Labels: size/S, okay to merge

#620 OSSM-4500 Allow execute disconnected testing group
  README.md
  pkg/tests/ossm/smcp_annotation_test.go
  pkg/tests/ossm/smcp_must_gather_test.go
  scripts/runtests.sh
Labels: size/S, okay to merge, tide/merge-method-squash

#622 TestOperatorCanUpdatePrometheusConfigMap
  pkg/tests/ossm/prometheus_scoped_scraping_test.go
Labels: size/XS, okay to merge

#623 OSSM-4671 Improve make information
  Makefile
Labels: size/M, okay to merge

#625 Updating read me information
  README.md
Labels: size/M, okay to merge

#624 Updating the GRPC SM yaml
  pkg/tests/tasks/security/authorization/ext_auth_test.go
Labels: size/XS, okay to merge
