Repository maistra/maistra-test-tool, pull requests merged in 2023-03, with the labels that each got.

#379 Use go install to properly install junit
  scripts/pipeline/run_all_tests.sh
  scripts/pipeline/run_one_test.sh
Labels: size/XS

#377 Adding new test case regarding OSSM-3515
  pkg/ossm/operator.go
  pkg/util/kube.go
  tests/test_cases.go
Labels: size/L

#381 Cleanup test_cases.go
  tests/test_cases.go
Labels: size/L

#382 Add fix to T35
  pkg/ossm/bug_istiopods.go
  pkg/util/kube.go
Labels: size/M

#380 Adding new subtest case to T40
  pkg/ossm/operator.go
Labels: size/L

#385 Maistra Test case for bug OSSM-2374
  pkg/ossm/bug_smm_delete_smmr.go
  pkg/ossm/yaml_configs.go
  pkg/util/kube.go
  tests/test_cases.go
Labels: size/L

#386 T40
  pkg/ossm/operator.go
Labels: size/XS

#387 Increase wait time for smcp ready in T40 execution
  pkg/ossm/operator.go
Labels: size/XS

#388 T40
  pkg/ossm/operator.go
Labels: size/XS

#389 fix T39 flaky test
  pkg/ossm/yaml_configs.go
Labels: size/M

#390 T40
  pkg/ossm/operator.go
Labels: size/XS

#391 avoid smcp deletion in T37
  pkg/tasks/security/authorization/externalauthorization.go
Labels: size/XS

#393 Deactivate T36 test case to avoid next test cases to fail
  pkg/ossm/bug_multiple_smcp.go
  tests/test_cases.go
Labels: size/S
