Repository maistra/maistra-test-tool, pull requests merged in 2023-06, with the labels that each got.

#558 OSSM-3987 Increase test coverage cluster wide
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/yaml/profiles/clusterWide.yaml
  pkg/util/oc/oc_struct.go
Labels: size/L, okay to merge

#544 OSSM-3871 TestSMCPAnnotations flaky test
  pkg/tests/ossm/deploy_on_infra_test.go
  pkg/tests/ossm/smcp_annotation_test.go
Labels: size/M, okay to merge

#564 Add TestPrometheusExtensionProvider
  pkg/tests/tasks/observability/custom_prometheus_test.go
Labels: size/L, okay to merge

#578 OSSM-3912 Unify install bookinfo and install/upgrade smcp test
  pkg/tests/non-dependant/smcp_install_test.go
  pkg/tests/non-dependant/yaml.vars.go
  pkg/tests/ossm/smoke_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
Labels: size/L, okay to merge

#584 Enable Sub test case: delete smcp in Smoke Test
  pkg/tests/ossm/smoke_test.go
Labels: size/M, okay to merge

#587 Update `ParseOCPVersion` reference in metallb
  pkg/metallb/install.go
Labels: size/XS, okay to merge

#586 OSSM-4072: validate routes created in SMCP installation
  pkg/tests/ossm/smoke_test.go
Labels: size/S, okay to merge

#590 Rollback to change of proxy startup time
  pkg/tests/ossm/smoke_test.go
Labels: size/S, okay to merge

#594 Return empty proxy when status cluster proxy does not exist
  pkg/util/oc/oc_struct.go
Labels: size/XS, okay to merge

#593 OSSM-3979 E2E test for ext-authz-grpc
  pkg/tests/tasks/security/authorization/ext_auth_test.go
Labels: size/M, okay to merge

#595 Update Readme
  README.md
Labels: size/XS, okay to merge

#596 OSSM-3995 Cluster-wide new test case related privileges to update SMMR
  pkg/tests/ossm/operator/clusterwide_mode_test.go
Labels: size/L, okay to merge

#598 OSSM-4223 Fix target file in must gather test case
  pkg/tests/ossm/smcp_must_gather_test.go
Labels: size/XS, okay to merge

#599 OSSM-3837 Fix errors on TestDeployOnInfraNodes
  pkg/tests/ossm/deploy_on_infra_test.go
Labels: size/S, okay to merge

#597 OSSM-4217 Fix issues with cert manager setup
  pkg/metallb/install.go
  pkg/tests/tasks/observability/custom_prometheus_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/security/certmanager/main_test.go
  pkg/tests/tasks/security/certmanager/yaml/cert-manager-operator.yaml
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
  pkg/util/oc/pod_commands.go
Labels: size/M, okay to merge

#600 OSSM-3837 TestDeployOnInfraNodes, fix patch and adding improvement to the test
  pkg/tests/ossm/deploy_on_infra_test.go
Labels: size/S, okay to merge

#568 OSSM-2027 : GatewayAPI and GatewayController
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
Labels: size/L, okay to merge

#601 OSSM-4358 Change SingleCluster federation test to work with multicluster also
  pkg/metallb/install.go
  pkg/tests/ossm-federation/federation_traffic_splitting_test.go
  pkg/tests/ossm-federation/main_test.go
Labels: size/M, okay to merge

#602 OSSM-4357 skip custom prometheus test case on version older than 4.11
  pkg/tests/tasks/observability/custom_prometheus_test.go
Labels: size/XS, okay to merge

#603 skip Deploy the Gateway-Controller Profile for version les than 2.4
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
Labels: size/XS, okay to merge

#604 skip certmanager for IBM Z&P
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/main_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
Labels: size/XS, okay to merge
