Repository maistra/maistra-test-tool, pull requests merged in 2023-10, with the labels that each got.

#633 OSSM-3647: Add tests for 3scale plugin
  pkg/tests/tasks/extensions/main_test.go
  pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
  pkg/tests/tasks/extensions/yaml/3scale-backend-service-entry.yaml
  pkg/tests/tasks/extensions/yaml/3scale-backend.yaml
  pkg/tests/tasks/extensions/yaml/3scale-system-service-entry.yaml
  pkg/tests/tasks/extensions/yaml/3scale-system.yaml
  pkg/tests/tasks/extensions/yaml/jwt-authn.tmpl.yaml
  pkg/tests/tasks/extensions/yaml/mesh.tmpl.yaml
  pkg/tests/tasks/extensions/yaml/wasm-plugin.tmpl.yaml
Labels: size/XL, okay to merge

#634 OSSM-3647: Add a test for feature flag `APPLY_WASM_PLUGINS_TO_INBOUND_ONLY` in v2.3
  pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
  pkg/tests/tasks/extensions/yaml/mesh.tmpl.yaml
Labels: size/M, okay to merge

#635 OSSM-3647: Add test for `APPLY_WASM_PLUGINS_TO_INBOUND_ONLY` in v2.4 and WASM plugin in SERVER mode
  pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
  pkg/tests/tasks/extensions/yaml/wasm-plugin.tmpl.yaml
Labels: size/S, okay to merge

#636 MTT: Prevent the route for Additional Ingress
  pkg/tests/ossm/route_prevent_additional_ingress_test.go
Labels: size/M, okay to merge
