Repository maistra/maistra-test-tool, pull requests merged in 2023-05, with the labels that each got.

#538 OSSM-3893 Prepend SMCP version to testcase name
  scripts/runtests.sh
Labels: size/XS, okay to merge

#541 OSSM-3483 Adding documentation script
  scripts/runtests.sh
Labels: size/S, okay to merge

#502 Update TestExternalCertificate to use x509
  pkg/tests/tasks/security/certificate/external_ca_test.go
Labels: size/L, okay to merge

#543 OSSM-3871 Fix Flaky test: TestCircuitBreaking
  pkg/tests/tasks/traffic/circuit_breaking_test.go
Labels: size/M, okay to merge

#545 OSSM-3600: Add test of integration with OpenShift Monitoring stack
  pkg/tests/tasks/observability/main_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/pod_commands.go
Labels: size/L, okay to merge

#550 Fix Bookinfo WaitReady() (must also wait for details-v1)
  pkg/app/bookinfo.go
Labels: size/XS, okay to merge

#551 OSSM-3928: Added the ext-auth image for IBM P platfrom
  images.yaml
  pkg/tests/tasks/security/authorization/ext_auth_test.go
Labels: size/S, okay to merge

#519 OSSM-3802 Add TestDiscoverySelectors
  pkg/tests/ossm/discovery_selectors_test.go
Labels: size/L, okay to merge

#546 OSSM-3871 Improve Apply String, template and file
  pkg/util/oc/oc_struct.go
  pkg/util/test/test_helper_setup.go
Labels: size/M, okay to merge

#540 OSSM-3878 ClusterWide increase test coverage
  pkg/tests/non-dependant/smcp_install_test.go
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/setup.go
  pkg/tests/ossm/yaml/profiles/clusterWide.yaml
Labels: size/L, okay to merge

#552 Cluster wide: merge subtest in basic SMCP test case
  pkg/tests/non-dependant/smcp_install_test.go
Labels: size/S, okay to merge

#553 Delete tnon used test in SMCPInstall
  pkg/tests/non-dependant/smcp_install_test.go
Labels: size/S, okay to merge

#554 OSSM-3958 fix test case TestOpenShiftMonitoring
  pkg/tests/tasks/observability/openshift_monitoring_test.go
Labels: size/XS, okay to merge

#555 OSSM-3962: Add test for cacerts secret provided by cert-manager
  pkg/tests/tasks/security/certificate/cert_manager_test.go
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/main_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/tests/tasks/security/certmanager/yaml/cacerts/cacerts.yaml
  pkg/tests/tasks/security/certmanager/yaml/cacerts/mesh.yaml
  pkg/tests/tasks/security/certmanager/yaml/cert-manager-operator.yaml
  pkg/tests/tasks/security/certmanager/yaml/istio-csr/istio-ca.yaml
  pkg/tests/tasks/security/certmanager/yaml/istio-csr/istio-csr.yaml
  pkg/tests/tasks/security/certmanager/yaml/istio-csr/mesh.yaml
  pkg/tests/tasks/security/certmanager/yaml/root-ca.yaml
  pkg/util/check/assert/output.go
  pkg/util/check/common/output.go
  pkg/util/test/suite.go
  pkg/util/test/test_helper_setup.go
Labels: size/XL, okay to merge

#557 Fix nil pointer in setupTestHelper.Run()
  pkg/util/test/suite.go
Labels: size/XS, okay to merge

#556 OSSM-3982: use the latest tag on the main branch
  .github/workflows/main.yml
Labels: size/XS, okay to merge

#559 OSSM-3967 Fix Cert manager test cases
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/main_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
  pkg/util/test/test_helper_setup.go
  pkg/util/version/version.go
Labels: size/M, okay to merge

#565 OSSM-3984: Add custom Kiali to TestOpenShiftMonitoring
  pkg/tests/tasks/observability/main_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/observability/yaml/cluster-monitoring-config.tmpl.yaml
  pkg/tests/tasks/observability/yaml/enable-prometheus-metrics.yaml
  pkg/tests/tasks/observability/yaml/istio-proxy-monitor.yaml
  pkg/tests/tasks/observability/yaml/istiod-monitor.yaml
  pkg/tests/tasks/observability/yaml/kiali-user-workload-monitoring.tmpl.yaml
  pkg/tests/tasks/observability/yaml/mesh.tmpl.yaml
Labels: size/L, okay to merge

#570 Fix TestPluginCaCert
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/tests/tasks/security/certmanager/yaml/cacerts/mesh.yaml
Labels: size/XS, okay to merge

#572 OSSM-3420: Fix TestCircuitBreaking in IPv6 stack
  pkg/tests/ossm/yaml/smcp.yaml
  pkg/tests/tasks/traffic/circuit_breaking_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/service_commands.go
Labels: size/S, okay to merge

#573 OSSM-3418: Fix TestAuthPolicy on IPv6 stack
  pkg/tests/ossm/setup.go
  pkg/tests/ossm/yaml/smcp.yaml
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
Labels: size/M, okay to merge

#575 OSSM-3423: Fix TestIngressWithoutTlsTermination on IPv6
  pkg/app/yaml/nginx.conf
Labels: size/XS, okay to merge

#574 OSSM-3423: Fix TestSecureGateways on IPv6
  images.yaml
Labels: size/XS, okay to merge

#577 OSSM-3424: Fix egress traffic tests on IPv6 cluster
  pkg/app/nginx.go
  pkg/app/yaml/nginx-mesh-external-mtls.conf
  pkg/app/yaml/nginx-mesh-external-tls.conf
  pkg/tests/tasks/traffic/egress/access_external_services_test.go
  pkg/tests/tasks/traffic/egress/egress_common.go
  pkg/tests/tasks/traffic/egress/egress_gateways_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_file_mount_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_sds_test.go
  pkg/tests/tasks/traffic/egress/egress_tls_origination_test.go
  pkg/tests/tasks/traffic/egress/yaml/external-httpbin-http-gateway.yaml
  pkg/tests/tasks/traffic/egress/yaml/external-httpbin.yaml
  pkg/tests/tasks/traffic/egress/yaml/external-nginx-tls-istio-mutual-gateway.yaml
  pkg/tests/tasks/traffic/egress/yaml/external-nginx-tls-passthrough-gateway.yaml
  pkg/tests/tasks/traffic/egress/yaml/external-nginx.yaml
  pkg/tests/tasks/traffic/egress/yaml/mesh-route-http-requests-to-https-port.yaml
  pkg/tests/tasks/traffic/egress/yaml/originate-mtls-sds-to-nginx.yaml
  pkg/tests/tasks/traffic/egress/yaml/originate-mtls-to-nginx.yaml
  pkg/tests/tasks/traffic/egress/yaml/originate-tls-to-nginx.yaml
  pkg/tests/tasks/traffic/egress/yaml_configs.go
  pkg/tests/tasks/traffic/egress/yaml_vars.go
Labels: size/XXL, okay to merge

#561 OSSM-3998 Fix OCP Parse for Certmanager
  pkg/tests/non-dependant/smcp_install_test.go
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/main_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/util/version/ocp_version.go
  pkg/util/version/smcp_version.go
  pkg/util/version/version.go
Labels: size/L, okay to merge

#576 Clean up apply retry code
  pkg/util/oc/oc_struct.go
Labels: size/M, okay to merge

#582 Fix failing TestEgressTLSOrigination due to a missing namespace
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_sds_test.go
  pkg/tests/tasks/traffic/egress/egress_tls_origination_test.go
Labels: size/XS, okay to merge
