Repository maistra/maistra-test-tool, pull requests merged in 2024-08, with the labels that each got.

#721 Fix openssl entrypoint in smcp annotation test
  pkg/tests/ossm/smcp_annotation_test.go
Labels: size/XS, okay to merge

#712 Add a test for native sidecars
  pkg/tests/tasks/injection/main_test.go
  pkg/tests/tasks/injection/native_sidecars_test.go
  pkg/tests/tasks/injection/tproxy_test.go
  pkg/tests/tasks/injection/yaml/mesh.tmpl.yaml
  pkg/util/version/ocp_version.go
Labels: size/L, okay to merge

#723 [OSSM-6092] Add ROSA env in the SMCP where it was missing + [OSSM-6886] remove hardcoded istio-system
  pkg/tests/ossm/bug_istiopods_test.go
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/prometheus_scoped_scraping_test.go
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/tests/ossm/smcp_secret_test.go
  pkg/tests/ossm/smm_test.go
  pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
  pkg/tests/tasks/extensions/yaml/mesh.tmpl.yaml
  pkg/tests/tasks/injection/yaml/mesh.tmpl.yaml
  pkg/tests/tasks/observability/custom_prometheus_test.go
  pkg/tests/tasks/security/certificate/alpn_filter_non_istio_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/tests/tasks/security/certmanager/yaml/cacerts/cacerts.yaml
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
Labels: size/L, okay to merge

#724 OSSM-6818: Update TestMustGather image repo
  pkg/util/env/env.go
Labels: size/XS, okay to merge

#722 Update bookinfo IBM images
  images.yaml
Labels: size/S, okay to merge

#726 OSSM-6930: Resolve certmanager conflict for IBM Z&P
  pkg/certmanageroperator/install.go
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/tests/tasks/security/certmanager/yaml/istio-csr/istio-csr.yaml
Labels: size/M, okay to merge

#727 OSSM-6943: Add test IOR with headless service
  pkg/tests/ossm/ior_test.go
Labels: size/M, okay to merge

#728 Remove oc replace
  pkg/tests/ossm/bug_istiopods_test.go
  pkg/tests/ossm/discovery_selectors_test.go
  pkg/tests/ossm/setup.go
  pkg/tests/ossm/tempo_tracing_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
Labels: size/M, okay to merge

#734 Fix stuck build in openshift-ci
  Dockerfile
Labels: size/XS, okay to merge

#731 OSSM-7992: Add test SMCP log levels
  pkg/tests/ossm/smcp_logging_test.go
Labels: size/M, okay to merge

#730 OSSM-6975: Add test IOR copies argocd.argoproj.io except instance label
  pkg/tests/ossm/ior_test.go
Labels: size/M, okay to merge

#735 Fix certmanager instability
  pkg/certmanageroperator/install.go
Labels: size/XS, okay to merge
