Repository maistra/maistra-test-tool, pull requests merged in 2024-01, with the labels that each got.

#644 update the cert-manager-operator version
  pkg/certmanageroperator/install.go
Labels: size/XS, okay to merge

#645 OSSM-5596:Skip Web Assembly IBM P/Z
  pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
Labels: size/XS, okay to merge

#640 Adding skip test when the SMCP it's not the latest
  pkg/tests/ossm/smm_test.go
  pkg/util/env/env.go
  scripts/runtests.sh
Labels: size/S, okay to merge

#647 [OSSM-5683] Improve waiting for CSV is ready
  .gitignore
  pkg/certmanageroperator/install.go
  pkg/tests/ossm/deploy_on_infra_test.go
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/util/operator/operators.go
Labels: size/M, okay to merge

#649 [OSSM-5574] Update GatewayAPI version for OSSM2.5
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
  pkg/util/gatewayapi/gatewayapi.go
Labels: size/M, okay to merge

#650 [OSSM-5713] Add test for maistra.io/exclude-cni label
  pkg/tests/ossm/deploy_on_infra_test.go
Labels: size/M, okay to merge

#648 OSSM-5382: Fixing the BI test case
  images.yaml
  pkg/tests/tasks/traffic/common.go
  pkg/tests/tasks/traffic/fault_injection_test.go
  pkg/tests/tasks/traffic/request_routing_test.go
  pkg/tests/tasks/traffic/request_timeouts_test.go
  pkg/tests/tasks/traffic/traffic_shifting_test.go
  testdata/resources/html/productpage-normal-user-v1.html
  testdata/resources/html/productpage-normal-user-v2.html
  testdata/resources/html/productpage-normal-user-v3.html
  testdata/resources/html/productpage-test-user-v2-rating-unavailable.html
  testdata/resources/html/productpage-test-user-v2.html
Labels: size/L, okay to merge

#653 OSSM-5819: Update the curl image tag
  pkg/tests/ossm/initcontainer_test.go
Labels: size/XS, okay to merge

#652 OSSM-4847: Increase test coverage over Cluster Wide test case
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/util/oc/pod_commands.go
Labels: size/L, ok-to-test, okay to merge

#654 update cert manager version
  pkg/certmanageroperator/install.go
Labels: size/XS, okay to merge

#655 OSSM-5843: update the ARM group
  pkg/tests/non-dependant/bug_multiple_smcp_test.go
  pkg/tests/ossm/bug_istiopods_test.go
  pkg/tests/ossm/deploy_on_infra_test.go
  pkg/tests/ossm/discovery_selectors_test.go
  pkg/tests/ossm/initcontainer_test.go
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/operator/operator_deadlock_test.go
  pkg/tests/ossm/operator/operator_readiness_test.go
  pkg/tests/ossm/prometheus_scoped_scraping_test.go
  pkg/tests/ossm/ratelimit_test.go
  pkg/tests/ossm/route_prevent_additional_ingress_test.go
  pkg/tests/ossm/smcp_addons_test.go
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/tests/ossm/smm_test.go
  pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
  pkg/tests/tasks/observability/custom_prometheus_test.go
  pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/security/authentication/auth_test.go
  pkg/tests/tasks/security/authentication/mtls_migration_test.go
  pkg/tests/tasks/security/authorization/deny_test.go
  pkg/tests/tasks/security/authorization/jwt_test.go
  pkg/tests/tasks/security/authorization/trust_domain_test.go
  pkg/tests/tasks/traffic/egress/access_external_services_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_file_mount_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_sds_test.go
  pkg/tests/tasks/traffic/egress/egress_tls_origination_test.go
  pkg/tests/tasks/traffic/egress/egress_wildcard_hosts_test.go
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
  pkg/tests/tasks/traffic/ingress/ingress_gateways_test.go
  pkg/tests/tasks/traffic/ingress/ingress_without_tls_termination_test.go
  pkg/tests/tasks/traffic/traffic_mirroring_test.go
Labels: size/M, okay to merge

#656 OSSM-5846: Updated image to install the applications on the ARM
  images.yaml
  pkg/tests/ossm/smm_test.go
  pkg/tests/tasks/security/authorization/ext_auth_test.go
  pkg/tests/tasks/security/authorization/tcp_test.go
  pkg/tests/tasks/traffic/circuit_breaking_test.go
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/tests/tasks/traffic/traffic_tcp_shifting_test.go
Labels: size/S, okay to merge
