Repository maistra/maistra-test-tool, pull requests merged in 2024-10, with the labels that each got.

#747 Improve string comparison for privileged_pods and smcp_logging tests
  pkg/tests/ossm/privileged_pods_test.go
  pkg/tests/ossm/smcp_logging_test.go
Labels: size/M, okay to merge

#745 OSSM-8078 Automate Test Expose Grpc With Https Gateway
  images.yaml
  pkg/app/grpcurl.go
  pkg/tests/tasks/traffic/ingress/grpc_https_gateway_test.go
  pkg/tests/tasks/traffic/ingress/yaml/grpc_echo_server.yaml
  pkg/tests/tasks/traffic/ingress/yaml/grpc_https_gateway.yaml
  pkg/util/ns/namespaces.go
  sampleCerts/grpc.example.com/grpc.example.com.crt
  sampleCerts/grpc.example.com/grpc.example.com.key
Labels: size/L

#749 Skip P/Z in TestExposeGrpcWithHttpsGateway for now
  pkg/tests/tasks/traffic/ingress/grpc_https_gateway_test.go
Labels: size/XS, okay to merge

#750 OSSM-8225 Add test for mesh member metrics
  pkg/tests/ossm/discovery_selectors_test.go
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/prometheus_scoped_scraping_test.go
  pkg/tests/ossm/setup.go
  pkg/tests/ossm/yaml/smcp.yaml
Labels: size/L, okay to merge

#754 [OSSM-8258] Test for addons disable
  pkg/tests/ossm/operator/addons_disable_test.go
Labels: size/M, okay to merge

#753 OSSM-8251: Add test for file upload case
  pkg/app/sleep.go
  pkg/tests/tasks/security/authorization/ext_auth_test.go
Labels: size/L, okay to merge

#756 [OSSM-8260] Add test for custom routes in grafana/prometheus
  pkg/tests/ossm/operator/addons_disable_test.go
  pkg/tests/ossm/smcp_addons_test.go
  pkg/tests/ossm/yaml/addons-route-patch.yaml
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
Labels: size/L, okay to merge

#758 OSSM-8252: Add pod locality controller fails to update pod test
  pkg/tests/ossm/bug_istiopods_test.go
Labels: size/M, okay to merge

#759 OSSM-8253: Update and add reference to test T52
  pkg/tests/ossm/smcp_secret_test.go
Labels: size/S, okay to merge
