Repository maistra/maistra-test-tool, pull requests merged in 2024-03, with the labels that each got.

#665 OSSM-6008: Use Kiali token to fetch metrics from Thanos
  pkg/tests/tasks/observability/main_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/observability/yaml/kiali-cluster-monitoring-view.tmpl.yaml
  pkg/tests/tasks/observability/yaml/kiali-user-workload-monitoring.tmpl.yaml
Labels: size/M, okay to merge

#666 OSSM-5999: Remove Kiali fields, which are reconciled by Istio Operator
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/observability/yaml/kiali-user-workload-monitoring.tmpl.yaml
Labels: size/S, okay to merge

#667 Fix typo in openshift_monitoring_test
  pkg/tests/tasks/observability/openshift_monitoring_test.go
Labels: size/XS, okay to merge

#668 Fix invalid token in openshift_monitoring_test
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/pod_commands.go
Labels: size/M, okay to merge

#669 Fix tls error message check on FIPS cluster
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/util/check/assert/http_response.go
  pkg/util/check/common/http_response.go
Labels: size/M, okay to merge

#670 [OSSM-6090] Fix ROSA specific value for TestOpenShiftMonitoring
  pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/observability/yaml/federated-monitoring-mesh.tmpl.yaml
  pkg/tests/tasks/observability/yaml/mesh.tmpl.yaml
Labels: size/S, okay to merge

#671 Fix nil when request fails without response body
  pkg/util/check/common/http_response.go
Labels: size/XS, okay to merge

#673 update the ior and skip arm
  pkg/tests/ossm/ior_test.go
Labels: size/XS, okay to merge

#675 Update ext-authz images
  images.yaml
Labels: size/XS, okay to merge
