Repository maistra/maistra-test-tool, pull requests merged in 2024-05, with the labels that each got.

#686 OSSM-6567: MTT update_ns_package for Traffic test suite
  pkg/tests/tasks/traffic/circuit_breaking_test.go
  pkg/tests/tasks/traffic/egress/egress_wildcard_hosts_test.go
  pkg/tests/tasks/traffic/fault_injection_test.go
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
  pkg/tests/tasks/traffic/ingress/ingress_gateways_test.go
  pkg/tests/tasks/traffic/ingress/ingress_without_tls_termination_test.go
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/tests/tasks/traffic/request_routing_test.go
  pkg/tests/tasks/traffic/request_timeouts_test.go
  pkg/tests/tasks/traffic/traffic_mirroring_test.go
  pkg/tests/tasks/traffic/traffic_shifting_test.go
  pkg/tests/tasks/traffic/traffic_tcp_shifting_test.go
Labels: size/L, okay to merge

#688 [OSSM-6574]: MTT-update the httpbin image for IBM-Z
  images.yaml
Labels: size/XS, okay to merge

#690 [OSSM-6582] MTT: Fixing the flaky for the Prometheus pod
  pkg/tests/tasks/observability/custom_prometheus_test.go
Labels: size/XS, okay to merge

#689 [OSSM-6572] MTT: Delete redunduncies in test pkg import, cleanup
  pkg/tests/ossm/prometheus_scoped_scraping_test.go
  pkg/tests/ossm/ratelimit_test.go
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/tests/ossm/smm_test.go
  pkg/tests/ossm/smoke_test.go
  pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
  pkg/tests/tasks/traffic/circuit_breaking_test.go
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
Labels: size/M, okay to merge
