Repository maistra/maistra-test-tool, pull requests merged in 2024-07, with the labels that each got.

#701 [OSSM-6761] Use the correct Operator version (not SMCP version)
  pkg/tests/ossm/smm_test.go
  pkg/tests/ossm/smoke_test.go
  pkg/util/env/env.go
  pkg/util/version/operator_version.go
  scripts/runtests.sh
Labels: size/M, okay to merge

#702 [OSSM-6759] Bump ubi version in test container
  Dockerfile
Labels: size/XS, okay to merge

#699 [OSSM-6737] Verify that Jaeger is not created by default
  pkg/tests/ossm/smoke_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
Labels: size/M, okay to merge

#698 [OSSM-6738] MTT: GatewayAPI is enabled by default in ClusterWide mode
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
  pkg/util/gatewayapi/gatewayapi.go
Labels: size/L, okay to merge

#704 Update certmanageroperator to get version dynamicly
  pkg/certmanageroperator/install.go
  pkg/util/operator/operators.go
Labels: size/S, okay to merge

#705 Hotfix for installing certmanageroperator
  pkg/certmanageroperator/install.go
Labels: okay to merge

#706 OSSM-6784: Fix TestPluginCaCert flakiness
  pkg/tests/tasks/security/certmanager/yaml/cacerts/mesh.yaml
Labels: size/XS, okay to merge

#707 Update bookinfo samples from maistra/istio 2.6
  pkg/app/yaml/bookinfo-gateway.yaml
  pkg/app/yaml/bookinfo.yaml
Labels: size/XS, okay to merge

#708 Fix tests after changes in validation webhook
  pkg/tests/non-dependant/bug_multiple_smcp_test.go
  pkg/tests/non-dependant/olm_webhooks_test.go
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
Labels: size/L, okay to merge

#709 OSSM-6817: Update TestMustGather with new must-gather container
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/util/env/env.go
Labels: size/M, okay to merge

#710 OSSM-6403: Add basic tests for TPROXY interception mode
  pkg/app/httpbin.go
  pkg/app/sleep.go
  pkg/tests/tasks/traffic/tproxy_test.go
Labels: size/M, okay to merge

#711 OSSM-6820: updating the arm images
  images.yaml
Labels: size/XS, okay to merge

#713 OSSM-6832: update_bi_image_2.6
  images.yaml
Labels: size/M, okay to merge

#716 OSSM-6817: Update 2.6.0 must-gather container source
  pkg/util/env/env.go
Labels: size/XS, okay to merge

#715 Add new error message to notify that connection between product-details doesn't work
  pkg/tests/tasks/traffic/traffic_shifting_test.go
Labels: size/XS, okay to merge

#717 [OSSM-6824] Update testssl image to use openssl3
  images.yaml
  pkg/tests/ossm/testssl_test.go
Labels: size/S, okay to merge

#714 [OSSM-6734] Test coverage for Tempo/Otel integration
  images.yaml
  pkg/app/minio.go
  pkg/certmanageroperator/install.go
  pkg/certmanageroperator/yaml/cert-manager-operator.yaml
  pkg/tempo/install.go
  pkg/tempo/yaml/open-telemetry-operator.yaml
  pkg/tempo/yaml/tempo-operator.yaml
  pkg/tempo/yaml/tempoStack.yaml
  pkg/tests/ossm/deploy_on_infra_test.go
  pkg/tests/ossm/tempo_tracing_test.go
  pkg/tests/tasks/observability/custom_prometheus_test.go
  pkg/util/oc/oc.go
  pkg/util/oc/oc_struct.go
  pkg/util/operator/operators.go
Labels: size/XL, okay to merge

#718 [OSSM-6858] Use Route for minio instead of incluster hostname
  pkg/app/minio.go
Labels: size/S, okay to merge

#719 updating arm images
  images.yaml
Labels: size/XS, okay to merge
