Repository maistra/maistra-test-tool, pull requests merged in 2024-06, with the labels that each got.

#691 Add ROSA support for TestRoutePreventAdditionalIngress test + version fix
  pkg/tests/ossm/route_prevent_additional_ingress_test.go
Labels: size/S, okay to merge

#692 Update files to be able to work with 2.6.x version
  README.md
  pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
  pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
  pkg/util/env/env.go
  pkg/util/gatewayapi/gatewayapi.go
  pkg/util/version/smcp_version.go
  scripts/runtests.sh
  templates/smcp-templates/v2.6/cr_2.6_default_template.yaml
Labels: size/M, okay to merge

#693 MTT: refactor namespaces
  pkg/tests/ossm/initcontainer_test.go
  pkg/tests/ossm/ratelimit_test.go
  pkg/tests/ossm/smcp_annotation_test.go
  pkg/tests/ossm/smcp_must_gather_test.go
  pkg/tests/ossm/smm_test.go
  pkg/tests/ossm/testssl_test.go
  pkg/tests/tasks/security/authentication/auth_test.go
  pkg/tests/tasks/security/authentication/mtls_migration_test.go
Labels: size/L, okay to merge

#695 OSSM-6731: added the 2.6 version for Smoke test
  pkg/tests/ossm/smoke_test.go
Labels: size/XS, okay to merge

#696 [OSSM-6732] Removed explicitly specified tracing type from SMCP files
  pkg/tests/ossm/deploy_on_infra_test.go
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/route_prevent_additional_ingress_test.go
  pkg/tests/ossm/smoke_test.go
  pkg/tests/ossm/yaml/smcp.yaml
  templates/smcp-templates/v2.5/cr_2.5_default_template.yaml
  templates/smcp-templates/v2.6/cr_2.6_default_template.yaml
Labels: size/M, okay to merge

#697 [OSSM-6747] Update log message in OSSM 2.6 for TestPluginCaCert test
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
Labels: size/S, okay to merge

#700 [OSSM-6739] Add test case for CNI resources prune
  pkg/tests/ossm/smoke_test.go
  pkg/util/cni/cni.go
  pkg/util/compare.go
Labels: size/M, okay to merge
