Repository maistra/maistra-test-tool, pull requests merged in 2024-02, with the labels that each got.

#657 Update 2.5 ARM testssl test
  images.yaml
  pkg/tests/ossm/testssl_test.go
Labels: size/S, okay to merge

#651 [OSSM-3903] Improve log step and log in current test cases
  pkg/tests/tasks/security/authentication/auth_test.go
  pkg/tests/tasks/security/authorization/tcp_test.go
  pkg/tests/tasks/security/authorization/trust_domain_test.go
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/util/oc/oc_struct.go
Labels: size/M, okay to merge

#658 OSSM-5446: fix IOR test case for 2.5 & ARM
  pkg/tests/ossm/ior_test.go
Labels: size/S, okay to merge

#660 update ibm-z bookinfo images to 2.4
  images.yaml
Labels: size/S, okay to merge

#662 update arm group for TestSMCPAnnotations
  pkg/tests/ossm/smcp_annotation_test.go
Labels: size/XS, okay to merge

#661 OSSM-5833: Unify curl call from sleep pod
  pkg/app/sleep.go
  pkg/tests/ossm/operator/clusterwide_mode_test.go
  pkg/tests/ossm/smoke_test.go
  pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
  pkg/tests/tasks/security/authentication/auth_test.go
  pkg/tests/tasks/security/authentication/mtls_migration_test.go
  pkg/tests/tasks/security/authorization/common.go
  pkg/tests/tasks/security/authorization/deny_test.go
  pkg/tests/tasks/security/authorization/ext_auth_test.go
  pkg/tests/tasks/security/authorization/jwt_test.go
  pkg/tests/tasks/security/authorization/tcp_test.go
  pkg/tests/tasks/security/authorization/trust_domain_test.go
  pkg/tests/tasks/security/certmanager/istio_csr_test.go
  pkg/tests/tasks/security/certmanager/plugin_ca_test.go
  pkg/tests/tasks/traffic/egress/access_external_services_test.go
  pkg/tests/tasks/traffic/egress/egress_common.go
  pkg/tests/tasks/traffic/egress/egress_gateways_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_file_mount_test.go
  pkg/tests/tasks/traffic/egress/egress_gateways_tls_sds_test.go
  pkg/tests/tasks/traffic/egress/egress_tls_origination_test.go
  pkg/tests/tasks/traffic/egress/egress_wildcard_hosts_test.go
Labels: size/XL, okay to merge

#659 OSSM-5873: Add test case for certificate revocation list
  .gitignore
  pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
  pkg/tests/tasks/traffic/ingress/yaml_vars.go
  pkg/tests/tasks/traffic/traffic_shifting_test.go
  pkg/util/check/assert/http_response.go
  pkg/util/check/common/http_response.go
  pkg/util/check/require/http_response.go
  pkg/util/curl/curl.go
  sampleCerts/bookinfo.com/bookinfo.com.crt
  sampleCerts/bookinfo.com/bookinfo.com.csr
  sampleCerts/bookinfo.com/bookinfo.com.key
  sampleCerts/generate.sh
  sampleCerts/helloworldv1/helloworld-v1.example.com.crt
  sampleCerts/helloworldv1/helloworld-v1.example.com.csr
  sampleCerts/helloworldv1/helloworld-v1.example.com.key
  sampleCerts/httpbin.example.com/example.com.crl
  sampleCerts/httpbin.example.com/example.com.crt
  sampleCerts/httpbin.example.com/example.com.key
  sampleCerts/httpbin.example.com/httpbin-client-revoked.example.com.crt
  sampleCerts/httpbin.example.com/httpbin-client-revoked.example.com.csr
  sampleCerts/httpbin.example.com/httpbin-client-revoked.example.com.key
  sampleCerts/httpbin.example.com/httpbin-client.example.com.crt
  sampleCerts/httpbin.example.com/httpbin-client.example.com.csr
  sampleCerts/httpbin.example.com/httpbin-client.example.com.key
  sampleCerts/httpbin.example.com/httpbin.example.com.crt
  sampleCerts/httpbin.example.com/httpbin.example.com.csr
  sampleCerts/httpbin.example.com/httpbin.example.com.key
  sampleCerts/httpbin.example.com/index.txt
Labels: size/XL, okay to merge

#664 update ibm-z bookinfo images
  images.yaml
Labels: size/S, okay to merge
