Repository maistra/maistra-test-tool, pull requests merged in 2024-09, with the labels that each got.

#736 Fix gateway issue in ior test
  pkg/tests/ossm/ior_test.go
Labels: size/XS, okay to merge

#737 Add namespace cleanup after clusterwide test
  pkg/tests/ossm/discovery_selectors_test.go
Labels: size/XS, okay to merge

#738 OSSM-8002: test with privileged pods with explicitly set secuityContext
  pkg/app/sleep.go
  pkg/tests/ossm/privileged_pods_test.go
  pkg/util/version/operator_version.go
Labels: size/L, okay to merge

#739 [OSSM-8128] Use comunity prometheus operator
  pkg/prometheusoperator/install.go
  pkg/prometheusoperator/yaml/custom-prometheus-operator.yaml
  pkg/prometheusoperator/yaml/prometheus-instance.yaml
  pkg/tests/tasks/observability/custom_prometheus_test.go
  pkg/util/prometheus/prometheus_struct.go
Labels: size/L, okay to merge

#741 [OSSM-8141] Fix missing Tproxy label in httpbin deployment (when TProxy=true) + changed apps in native sidecars test from TProxy to normal variant
  pkg/app/httpbin.go
  pkg/tests/tasks/injection/native_sidecars_test.go
  pkg/tests/tasks/injection/tproxy_test.go
Labels: size/XS, okay to merge

#743 [OSSM-8154] Hotfix for cleaning custom prometheus operator
  pkg/tests/tasks/observability/custom_prometheus_test.go
Labels: size/XS, okay to merge

#740 [OSSM-8136] Add Kiali version into kiali cr + improve stability of TestOpenShiftMonitoring test
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/observability/yaml/kiali-user-workload-monitoring.tmpl.yaml
  pkg/util/env/env.go
Labels: size/M, okay to merge

#742 Add waiting for prometheus target in custom prometheus and federated openshift monitoring tests
  pkg/tests/tasks/observability/custom_prometheus_test.go
  pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
  pkg/util/prometheus/prometheus.go
  pkg/util/prometheus/prometheus_struct.go
Labels: size/M, okay to merge

#744 [OSSM-8154] Remove Custom Prometheus operator and test
  pkg/prometheusoperator/install.go
  pkg/prometheusoperator/yaml/custom-prometheus-operator.yaml
  pkg/prometheusoperator/yaml/prometheus-instance.yaml
  pkg/tests/tasks/observability/custom_prometheus_test.go
Labels: size/L, okay to merge

#746 Fix expected output for uid/uid after base image change
  pkg/tests/ossm/privileged_pods_test.go
Labels: size/XS, okay to merge
