Repository maistra/maistra-test-tool, pull requests merged in 2024-11, with the labels that each got.

#763 OSSM-1514: Expand Disconnected test cases
  pkg/tests/non-dependant/bug_multiple_smcp_test.go
  pkg/tests/non-dependant/olm_webhooks_test.go
  pkg/tests/ossm/bug_istiopods_test.go
  pkg/tests/ossm/bug_rolebinding_test.go
  pkg/tests/ossm/discovery_selectors_test.go
  pkg/tests/ossm/ior_test.go
  pkg/tests/ossm/prometheus_scoped_scraping_test.go
  pkg/tests/ossm/route_prevent_additional_ingress_test.go
  pkg/tests/tasks/injection/native_sidecars_test.go
  pkg/tests/tasks/injection/tproxy_test.go
  pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
  pkg/tests/tasks/observability/openshift_monitoring_test.go
  pkg/tests/tasks/security/authentication/mtls_migration_test.go
  pkg/tests/tasks/security/authorization/deny_test.go
  pkg/tests/tasks/security/authorization/ext_auth_test.go
  pkg/tests/tasks/security/authorization/http_test.go
  pkg/tests/tasks/security/authorization/trust_domain_test.go
  pkg/tests/tasks/security/certificate/external_ca_test.go
  pkg/tests/tasks/traffic/egress/access_external_services_test.go
  pkg/tests/tasks/traffic/fault_injection_test.go
  pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
  pkg/tests/tasks/traffic/ingress/ingress_gateways_test.go
  pkg/tests/tasks/traffic/request_routing_test.go
  pkg/tests/tasks/traffic/request_timeouts_test.go
  pkg/tests/tasks/traffic/traffic_mirroring_test.go
  pkg/tests/tasks/traffic/traffic_shifting_test.go
Labels: size/L, okay to merge

#767 Stability improvements for IOR tests
  pkg/tests/ossm/ior_test.go
Labels: size/M, okay to merge

#768 Fix hardcoded sleep image
  pkg/tests/ossm/initcontainer_test.go
Labels: size/XS, okay to merge
